(def-sdl-event-type
  (*traits-sdl-noevent* SDL_NOEVENT)
  (*traits-sdl-activeevent* SDL_ACTIVEEVENT)
  (*traits-sdl-keydown* SDL_KEYDOWN)
  (*traits-sdl-keyup* SDL_KEYUP)
  (*traits-sdl-mousemotion* SDL_MOUSEMOTION)
  (*traits-sdl-mousebuttondown* SDL_MOUSEBUTTONDOWN)
  (*traits-sdl-mousebuttonup* SDL_MOUSEBUTTONUP)
  (*traits-sdl-joyaxismotion* SDL_JOYAXISMOTION)
  (*traits-sdl-joyballmotion* SDL_JOYBALLMOTION)
  (*traits-sdl-joyhatmotion* SDL_JOYHATMOTION)
  (*traits-sdl-joybuttondown* SDL_JOYBUTTONDOWN)
  (*traits-sdl-joybuttonup* SDL_JOYBUTTONUP)
  (*traits-sdl-quit* SDL_QUIT)
  (*traits-sdl-syswmevent* SDL_SYSWMEVENT)
  (*traits-sdl-videoresize* SDL_VIDEORESIZE)
  (*traits-sdl-videoexpose* SDL_VIDEOEXPOSE)
  (*traits-sdl-userevent* SDL_USEREVENT))
